memory:
  flash_base: 0x00000000
  flash_size: 524288
  sram_base: 0x20000000
  sram_size: 131072
  periph_base: 0x40000000
  periph_size: 0x00100000
  bitband_sram_base: 0x22000000
  bitband_sram_size: 0x02000000
  bitband_periph_base: 0x42000000
  bitband_periph_size: 0x02000000

gpio:
  kind: tm4c123
  port_size: 0x1000
  ports:
    A: 0x40004000
    B: 0x40005000
    C: 0x40006000
    D: 0x40007000
    E: 0x40024000
    F: 0x40025000
  offsets:
    data: 0x000
    dir: 0x400
    den: 0x51C
    lock: 0x520
    cr: 0x524
    is: 0x404
    ibe: 0x408
    iev: 0x40C
    im: 0x410
    ris: 0x414
    mis: 0x418
    icr: 0x41C
    afsel: 0x420

sysctl:
  base: 0x400FE000
  registers:
    rcgcgpio: 0x608
    rcgctimer: 0x604
    rcgcuart: 0x618
    rcgcssi: 0x61C
    rcgci2c: 0x620
    rcgcpwm: 0x640
    rcgcadc: 0x638

pins:
  pin_masks:
    PIN0: 0x01
    PIN1: 0x02
    PIN2: 0x04
    PIN3: 0x08
    PIN4: 0x10
    PIN5: 0x20
    PIN6: 0x40
    PIN7: 0x80
  leds:
    RED: 0x02
    BLUE: 0x04
    GREEN: 0x08
  switches:
    SW1: 0x10
    SW2: 0x01

nvic:
  irq:
    GPIO_PORTA: 0
    GPIO_PORTB: 1
    GPIO_PORTC: 2
    GPIO_PORTD: 3
    GPIO_PORTE: 4
    GPIO_PORTF: 30
  irq_offset: 16

